---
- name: Installing dependencies 
  apt:
    name:  
      - apt-transport-https
      - software-properties-common 
      - wget
    state: latest

- name: Add Grafana APT repository key
  apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present

- name: Add Grafana APT repository
  apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main
    state: present

- name: Update APT package cache
  apt:
    update_cache: yes

- name: Install Grafana
  apt:
    name: grafana
    state: present

- name: Start and enable Grafana service
  systemd:
    name: grafana-server
    enabled: yes
    state: started

- name: Add InfluxDB APT key
  apt_key:
    url: https://repos.influxdata.com/influxdb.key
    state: present

- name: Add InfluxDB APT repository
  apt_repository:
    repo: deb https://repos.influxdata.com/ubuntu bionic stable
    state: present

- name: Install InfluxDB
  apt:
    name: influxdb
    state: present

- name: Start and enable InfluxDB service
  systemd:
    name: influxdb
    enabled: yes
    state: started



- name: Installing prerequisites in Ubuntu
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - apt-transport-https
    - software-properties-common
  when: ansible_distribution == "Ubuntu"

- name: Install Prometheus on Ubuntu
  apt:
    name: prometheus
    state: present
  when: ansible_distribution == "Ubuntu"

- name: Update Prometheus on Ubuntu
  apt:
    name: prometheus
    state: latest
  when: ansible_distribution == "Ubuntu"


- name: Starting/restarting prometheus
  service:
    name: prometheus
    state: restarted
    enabled: true

