- name: Installing dependencies
  apt:
    name:
      - libapache2-mod-php
      - apache2
      - php
      - php-mysql
      - mysql-server
    state: latest 

- name: Starting apache2 service
  service:
    name: apache2
    state: started
    enabled: true

